language: "node_js"

node_js:
  - "8"
  - "node"

install:
  - npm ci

script:
  - npm run lint
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml

notifications:
  email:
    false